include("exercism/leap-year-tests.jl")
include("exercism/nucleotide-count-tests.jl")
include("exercism/pangram-tests.jl")
include("exercism/caesar-cipher-tests.jl")
include("exercism/difference-of-squares-tests.jl")
include("exercism/raindrops-tests.jl")
